#!/bin/bash

# Symine Docker Helper Script
# Quick reference for common Docker commands

echo "🐳 Symine Docker Helper"
echo "======================="
echo ""
echo "📦 Container Management:"
echo "  docker-compose up -d              Start all services"
echo "  docker-compose stop               Stop all services"
echo "  docker-compose down               Stop and remove containers"
echo "  docker-compose ps                 Show running containers"
echo "  docker-compose logs -f            Follow logs"
echo "  docker-compose logs -f app        Follow app logs"
echo ""
echo "🔧 Application Commands:"
echo "  docker-compose exec app php bin/console ...    Run Symfony command"
echo "  docker-compose exec app composer install      Install dependencies"
echo "  docker-compose exec app composer update       Update dependencies"
echo "  docker-compose exec app php bin/console cache:clear    Clear cache"
echo ""
echo "🗄️  Database:"
echo "  docker-compose exec app php bin/console doctrine:migrations:migrate"
echo "  docker-compose exec app php bin/console doctrine:fixtures:load"
echo "  docker-compose exec app php bin/console doctrine:schema:update --dump-sql"
echo "  docker-compose exec mysql mysql -uroot -proot redmine_development"
echo ""
echo "🧪 Testing:"
echo "  docker-compose exec test vendor/bin/phpunit tests/E2E"
echo "  docker-compose exec test vendor/bin/phpunit tests/E2E/LoginTest.php"
echo "  docker-compose exec test vendor/bin/phpunit --testdox"
echo ""
echo "🔍 Debugging:"
echo "  docker-compose logs app           View app logs"
echo "  docker-compose logs mysql         View MySQL logs"
echo "  docker-compose exec app bash      Shell into app container"
echo "  docker-compose exec mysql bash    Shell into MySQL container"
echo ""
echo "🧹 Cleanup:"
echo "  docker-compose down               Stop and remove containers"
echo "  docker-compose down -v            Stop, remove containers and volumes"
echo "  docker system prune              Clean up unused Docker resources"
echo ""
echo "🔄 Reset Everything:"
echo "  docker-compose down -v && ./docker-init.sh"
echo ""
echo "📚 More info: See DOCKER.md"
